# Generated by Django 5.1.7 on 2025-05-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarioFeriados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercicio",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Exercício"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendário de Feriados",
                "verbose_name_plural": "Calendários de Feriados",
                "ordering": ["exercicio"],
            },
        ),
        migrations.CreateModel(
            name="CargoComum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("detalhes", models.CharField(blank=True, max_length=250, null=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cargo Comum",
                "verbose_name_plural": "Cargos Comuns",
            },
        ),
        migrations.CreateModel(
            name="Numerador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercicio_num",
                    models.PositiveSmallIntegerField(verbose_name="exercício"),
                ),
                (
                    "ultimo_num",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="último número"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CargoChefia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("detalhes", models.CharField(blank=True, max_length=250, null=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "subordinacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.cargochefia",
                        verbose_name="Subordinado a",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo de Chefia",
                "verbose_name_plural": "Cargos de Chefia",
            },
        ),
        migrations.CreateModel(
            name="Feriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abon_app.calendarioferiados",
                        verbose_name="Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "matricula",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="matrícula"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "cargo_chefia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.cargochefia",
                        verbose_name="Cargo de Chefia",
                    ),
                ),
                (
                    "cargo_comum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.cargocomum",
                        verbose_name="Cargo Comum",
                    ),
                ),
                (
                    "credenciais",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Credenciais de Acesso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.CreateModel(
            name="ReqAbonada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_registro",
                    models.PositiveIntegerField(
                        unique_for_year=True, verbose_name="Número de Registro"
                    ),
                ),
                (
                    "momento_inicio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Pedido"
                    ),
                ),
                ("data_abonada", models.DateField(verbose_name="Dia da Abonada")),
                (
                    "eh_aniversario",
                    models.BooleanField(
                        default=False, verbose_name="Abonada Aniversário?"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("T", "Tramitando"),
                            ("D", "Deferido"),
                            ("I", "Indeferido"),
                            ("C", "Cancelado"),
                        ],
                        default="T",
                        max_length=1,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "momento_despacho",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Despacho"
                    ),
                ),
                (
                    "despacho",
                    models.BooleanField(default=True, verbose_name="Deferido?"),
                ),
                (
                    "justificativa",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Justificativa",
                    ),
                ),
                (
                    "momento_cancelamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Cancelamento"
                    ),
                ),
                (
                    "arquivado",
                    models.BooleanField(default=False, verbose_name="Arquivado?"),
                ),
                (
                    "cargo_chefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.cargochefia",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "chefe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="func_chefe",
                        to="abon_app.funcionario",
                        verbose_name="Chefia",
                    ),
                ),
                (
                    "requerente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="func_requerente",
                        to="abon_app.funcionario",
                        verbose_name="Requerente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sigla", models.CharField(max_length=10)),
                ("detalhes", models.CharField(blank=True, max_length=250, null=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.cargochefia",
                        verbose_name="responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.AddField(
            model_name="funcionario",
            name="lotacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="abon_app.setor",
                verbose_name="Lotação",
            ),
        ),
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_abonadas_ano",
                    models.PositiveSmallIntegerField(
                        default=10,
                        verbose_name="Quantidade Máxima de Abonadas Comuns por Ano",
                    ),
                ),
                (
                    "max_abonadas_mes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Quantidade Máxima de Abonadas Comuns por Mês",
                    ),
                ),
                (
                    "min_dias_antes_abonada",
                    models.PositiveSmallIntegerField(
                        default=2,
                        verbose_name="Antecedência Mínima para Solicitação de Abonada",
                    ),
                ),
                (
                    "setor_gestao_pessoas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="abon_app.setor",
                        verbose_name="Setor com Atribuição de Gestão de Pessoas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
            },
        ),
    ]
