# Generated by Django 5.1.7 on 2025-03-20 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoChefia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('detalhes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CargoComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('detalhes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('detalhes', models.CharField(max_length=250)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargochefia')),
            ],
        ),
    ]
