# Generated by Django 5.1.7 on 2025-03-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargochefia',
            options={'verbose_name': 'Cargo de Chefia', 'verbose_name_plural': 'Cargos de Chefia'},
        ),
        migrations.AlterModelOptions(
            name='cargocomum',
            options={'verbose_name': 'Cargo Comum', 'verbose_name_plural': 'Cargos Comuns'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='cargochefia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargocomum',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
