# Generated by Django 5.1.7 on 2025-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0002_alter_cargochefia_options_alter_cargocomum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargochefia',
            name='detalhes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cargocomum',
            name='detalhes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='detalhes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
