# Generated by Django 5.1.7 on 2025-03-20 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0003_alter_cargochefia_detalhes_alter_cargocomum_detalhes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargochefia', verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10, verbose_name='matrícula')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True)),
                ('cargo_chefia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargochefia', verbose_name='Cargo de Chefia')),
                ('cargo_comum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargocomum', verbose_name='Cargo Comum')),
                ('lotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abon_app.setor', verbose_name='Lotação')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
