# Generated by Django 5.1.7 on 2025-03-22 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0005_configuracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='deferimento_presumido',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='setor_gestao_pessoas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abon_app.setor', verbose_name='Setor com Atribuição de Gestão de Pessoas'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default='2001-01-01', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=10, unique=True, verbose_name='matrícula'),
        ),
    ]
