# Generated by Django 5.1.7 on 2025-03-23 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0007_remove_funcionario_email_funcionario_credenciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='credenciais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Credenciais de Acesso'),
        ),
    ]
