# Generated by Django 5.1.7 on 2025-03-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0008_remove_funcionario_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio_num', models.PositiveSmallIntegerField(verbose_name='exercício')),
                ('ultimo_num', models.PositiveBigIntegerField(default=0, verbose_name='último número')),
            ],
        ),
        migrations.CreateModel(
            name='ReqAbonada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.PositiveIntegerField(unique_for_year=True, verbose_name='Número de Registro')),
                ('momento_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_abonada', models.DateField(verbose_name='Dia da Abonada')),
                ('eh_aniversario', models.BooleanField(default=False, verbose_name='Abonada Aniversário?')),
                ('situacao', models.CharField(choices=[('T', 'Tramitando'), ('D', 'Deferido'), ('I', 'Indeferido'), ('C', 'Cancelado')], default='T', max_length=1, verbose_name='Situação')),
                ('momento_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Data do Despacho')),
                ('despacho', models.BooleanField(default=None, verbose_name='Deferido?')),
                ('justificativa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Justificativa')),
                ('momento_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Cancelamento')),
                ('arquivado', models.BooleanField(default=False, verbose_name='Arquivado?')),
                ('cargo_chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargochefia', verbose_name='Cargo')),
                ('chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_chefe', to='abon_app.funcionario', verbose_name='Chefia')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='func_requerente', to='abon_app.funcionario', verbose_name='Requerente')),
            ],
        ),
    ]
