# Generated by Django 5.1.7 on 2025-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0009_numerador_reqabonada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqabonada',
            name='despacho',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Deferido?'),
        ),
    ]
