# Generated by Django 5.1.7 on 2025-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0010_alter_reqabonada_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqabonada',
            name='despacho',
            field=models.BooleanField(default=True, verbose_name='Deferido?'),
        ),
    ]
