# Generated by Django 5.1.7 on 2025-04-01 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0011_alter_reqabonada_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargochefia',
            name='subordinacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='abon_app.cargochefia', verbose_name='Subordinado a'),
        ),
    ]
