# Generated by Django 5.1.7 on 2025-04-23 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abon_app', '0012_cargochefia_subordinacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioFeriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.PositiveSmallIntegerField(unique=True, verbose_name='Exercício')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Calendário de Feriados',
                'verbose_name_plural': 'Calendários de Feriados',
                'ordering': ['exercicio'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abon_app.calendarioferiados', verbose_name='Calendário')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
    ]
